### ISSUE TITLE
How to use reset()? 

### ISSUE THREAD

**Issue by iwknow** [rendro/vintageJS#18]
Hi. i am using Jquery version of vintageJS on my personal website. i want to have a drop down like this page. http://rendro.github.io/vintageJS/
I have difficulty of resetting the image to the origin. i have tried $('#myImage').reset(); but it doesn't work. 
Does any one have any suggestion?
Thanks!

**Comment by roysG** [comment]
Hi, 
see example:


 var options = {
        onError: function() {
            alert('ERROR');
        }
    };
    var effect = {
        vignette: 0.6,
        sepia: true
    };
    var vintageImg = $('img#yourImage').vintage(options, effect);

vintageImg.reset();

should works for you :)
