### ISSUE TITLE
Transparency Converted to Black

### ISSUE THREAD

**Issue by glassdimly** [rendro/vintageJS#23]
Hello,

Awesome library. 

One thing, when I apply contrast, sepia, or desaturate, the transparent parts of my PNG file are rendered black.

Is this the expected behavior? Is there any way to re-map that black color to transparency or any way to change this behavior?

Thanks,
Jeremy

**Comment by rendro** [comment]
The script shouldn't change values of the alpha channel. Maybe you'll need to change the mime property of the config object to "image/png". If not the image will be rendered as a JPEG. This is probably why you get black areas. 

Let me know if that solves the problem. If not I'll have a more detailed look into your issue. 

Thanks!
