### ISSUE TITLE
Delayed jQuery Calls in onStart

### ISSUE THREAD

**Issue by Wingpad** [rendro/vintageJS#25]
I am trying to use vintageJS on my website to allow users to perform some tweaks on a profile picture, part of this process is to allow them to dynamically change the effects applied to the image on the fly. These are just simple tweaks like set brightness to -34 and etc. I am trying to have an alert displayed when vintageJS starts working (to let users know the site is not just sitting there, hung up).  However, when I try to show the alert inside of the `onStart` callback it does not actually show up until after vintageJS has finished executing (i.e. when `onEnd` gets called). Here is how I have everything set up:

```
function onVintageStart() {
   console.log('start');
   $('#infoAlert1').offcanvas('show');
}

function onVintageFinish() {
    console.log('finish');
}
...
$('#crop-source').vintage({
    onStart: onVintageStart,
    onStop: onVintageFinish
});
vintageAPI = $('#crop-source').data('vintageJS');
```

What is happening is that I see "start" printed in the log but my alert does not appear until after I see finish printed in the log. I am using [Jasny's OffCanvas](http://jasny.github.io/bootstrap/javascript/#offcanvas) plugin to show/hide the alert but I have tested it with just a simple standard jQuery call like `$('.navbar-brand').text('VintageJS Rocks~!' );` (and it was not updated until after `onEnd` was called). Do you have any ideas as to what would be causing this? Any help would be appreciated, thanks!

**Comment by rendro** [comment]
Seems to be your $('#infoAlert1').offcanvas('show'); method which does things in an async fashion. the callback is called before the effect is calculated.

A way to resolve this would be to calculate the effect in a webworker. This is currently not supported, but I hope to add an example for web worker support in v2+
