### ISSUE TITLE
How to use apply()?

### ISSUE THREAD

**Issue by AhmedShamel** [rendro/vintageJS#29]
Can anyone give some codes that show how to use apply() ?

**Comment by rendro** [comment]
Per default vintageJS keeps the original image as a reference, so whenever you call `vintage(effect)` the effect will be calculated based on the original source. If you want to add an effect on top of another effect, you must call `apply()` in between. This will set the current effect as a source for the next effect.

So without calling apply, this is what will happen:
```javascript
vjsApi.vintage(effectA);
// image will only have effect A
vjsApi.vintage(effectB);
// image will only have effect B
```

If you call apply in between:

```javascript
vjsApi.vintage(effectA);
// image will only have effect A
vjsApi.apply();
vjsApi.vintage(effectB);
// image will only have effect A + effect B
```

**Comment by AhmedShamel** [comment]
Thanks
