### ISSUE TITLE
base64 ng-src

### ISSUE THREAD

**Issue by feof** [rendro/vintageJS#31]
Hi, 
I have this code:
<img vintage="sepia:true;contrast:-64" id="picture" class="preview" ng-src="{{item.croppedImage}}" />
64-encoded data URI.

Can I use vintagejs without filename ?
Tnx !!

**Comment by rendro** [comment]
I'll add support for base64 urls in v2.1

**Comment by rendro** [comment]
Just added support for base64 data uri and regular URIs for vintagejs. Next up is creating an angular directive. Probably in new repo. I'll keep you updated
